name: Simple Echo Test

on:
  push:
    branches: [ main ]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello to Steve
        run: echo "Привет, Стив! Твой CI/CD работает!"

      - name: Print Date
        run: date